# Setup
title: Moments of Clarity
tagline: ""
description: Writings to describe the thoughts swirling in my head when they slow down and reformulate.
baseurl: ""
url: https://old-anish.lakkapragada.com
paginate: 5
permalink: pretty
google_analytics_id: G-MY94EDEHE6

# About/contact
author:
  name: Anish Lakkapragada
  url: https://twitter.com/anish_lk
  email: anish.lakkapragada@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-leaflet

# Custom vars
version: 1.1.0
